<?php
echo "<!doctype html>\n";
echo "<html lang=\"en\">\n";
echo "\n";
echo "<head>\n";
echo "    <!-- Required meta tags -->\n";
echo "    <meta charset=\"utf-8\">\n";
echo "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\">\n";
echo "    <title>泥豪</title>\n";
echo "    <!--/google-fonts -->\n";
echo "    <link href=\"https://fonts.googleapis.com/css2?family=Hind+Siliguri:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\n";
echo "    <!--//google-fonts -->\n";
echo "    <!-- Template CSS -->\n";
echo "    <link rel=\"stylesheet\" href=\"assets/css/style-liberty.css\">\n";
echo "</head>\n";
echo "\n";
echo "<body>\n";
echo "    <!--/Header-->\n";
echo "    <header id=\"site-header\" class=\"fixed-top\">\n";
echo "        <div class=\"container\">\n";
echo "            <nav class=\"navbar navbar-expand-lg navbar-light stroke py-lg-0\">\n";
echo "                <h1><a class=\"navbar-brand pe-xl-5 pe-lg-4\" href=\"index.html\">\n";
echo "                        LO<span class=\"sublog\">GO</span>\n";
echo "                    </a></h1>\n";
echo "                <button class=\"navbar-toggler collapsed\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarScroll\" aria-controls=\"navbarScroll\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n";
echo "                    <span class=\"navbar-toggler-icon fa icon-expand fa-bars\"></span>\n";
echo "                    <span class=\"navbar-toggler-icon fa icon-close fa-times\"></span>\n";
echo "                </button>\n";
echo "                <div class=\"collapse navbar-collapse\" id=\"navbarScroll\">\n";
echo "                    <ul class=\"navbar-nav me-lg-auto my-2 my-lg-0 navbar-nav-scroll\">\n";
echo "                        <li class=\"nav-item\">\n";
echo "                            <a class=\"nav-link active\" aria-current=\"page\" href=\"index.html\">家</a>\n";
echo "                        </li>\n";
echo "                        <li class=\"nav-item\">\n";
echo "                            <a class=\"nav-link\" href=\"about.html\">关于</a>\n";
echo "                        </li>\n";
echo "                        <li class=\"nav-item\">\n";
echo "                            <a class=\"nav-link\" href=\"services.html\">服務</a>\n";
echo "                        </li>\n";
echo "                        <li class=\"nav-item dropdown\">\n";
echo "                            <a class=\"nav-link dropdown-toggle\" href=\"#Pages\" id=\"navbarDropdown\" role=\"button\" data-bs-toggle=\"dropdown\" aria-expanded=\"false\">\n";
echo "                                博客 <span class=\"fa fa-angle-down ms-1\"></span>\n";
echo "                            </a>\n";
echo "                            <ul class=\"dropdown-menu\" aria-labelledby=\"navbarDropdown\">\n";
echo "                                <li><a class=\"dropdown-item pt-2\" href=\"xiaowublog.xyz/Blog.html\">Blog 1</a></li>\n";
echo "                                <li><a class=\"dropdown-item\" href=\"xiaowublog.xyz/Blog2.html\">Blog 2 </a></li>\n";
echo "                                <li><a class=\"dropdown-item\" href=\"xiaowublog.xyz/Blog3.html\">Blog 3</a></li>\n";
echo "                                <li><a class=\"dropdown-item\" href=\"xiaowublog.xyz/Blog4.html\">Blog 4</a></li>\n";
echo "                                <li><a class=\"dropdown-item\" href=\"xiaowublog.xyz/Blog5.html\">Blog 5 </a></li>\n";
echo "                                <li><a class=\"dropdown-item\" href=\"#\">Blog 6</a></li>\n";
echo "                            </ul>\n";
echo "                        </li>\n";
echo "                       \n";
echo "                        <!--<li class=\"nav-item\">-->\n";
echo "                        <!--    <a class=\"nav-link\" href=\"#\">友情链接</a>-->\n";
echo "                        <!--</li>-->\n";
echo "\n";
echo "                    </ul>\n";
echo "                    \n";
echo "                        \n";
echo "\n";
echo "                    <!-- //toggle switch for light and dark theme -->\n";
echo "                    <!-- search popup -->\n";
echo "                    <div id=\"search\" class=\"w3lpop-overlay\">\n";
echo "                        <div class=\"w3lpopup\">\n";
echo "                            <form action=\"#formsearch\" method=\"GET\" class=\"d-flex\">\n";
echo "                                <input type=\"search\" placeholder=\"Search..\" name=\"search\" required=\"required\" autofocus>\n";
echo "                                <button type=\"submit\"><span class=\"fas fa-search\"></span></button>\n";
echo "                                <a class=\"close\" href=\"#formsearch\">&times;</a>\n";
echo "                            </form>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                    <!-- /search popup -->\n";
echo "                </div>\n";
echo "                <!-- toggle switch for light and dark theme -->\n";
echo "                <div class=\"mobile-position\">\n";
echo "                    <nav class=\"navigation\">\n";
echo "                        <div class=\"theme-switch-wrapper\">\n";
echo "                            <label class=\"theme-switch\" for=\"checkbox\">\n";
echo "                                <input type=\"checkbox\" id=\"checkbox\">\n";
echo "                                <div class=\"mode-container\">\n";
echo "                                    <i class=\"gg-sun\"></i>\n";
echo "                                    <i class=\"gg-moon\"></i>\n";
echo "                                </div>\n";
echo "                            </label>\n";
echo "                        </div>\n";
echo "                    </nav>\n";
echo "                </div>\n";
echo "                <!-- //toggle switch for light and dark theme -->\n";
echo "            </nav>\n";
echo "        </div>\n";
echo "    </header>\n";
echo "    <!--//Header-->\n";
echo "    <!-- breadcrumb -->\n";
echo "    <section class=\"w3l-about-breadcrumb\">\n";
echo "        <div class=\"breadcrumb-bg breadcrumb-bg-about py-5\">\n";
echo "            <div class=\"container py-lg-5 py-md-4\">\n";
echo "                <div class=\"w3breadcrumb-gids text-center pt-5\">\n";
echo "                    <div class=\"w3breadcrumb-right\">\n";
echo "                        <ul class=\"breadcrumbs-custom-path\">\n";
echo "                            <li><a href=\"index.html\">家</a></li>\n";
echo "                            <li class=\"active\"><span class=\"fas fa-angle-double-right mx-2\"></span> 服務</li>\n";
echo "                        </ul>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </section>\n";
echo "    <!--//breadcrumb-->\n";
echo "	<div style=\"margin: 8px auto; display: block; text-align:center;\">\n";
echo "\n";
echo "<!---728x90--->\n";
echo "\n";
echo " \n";
echo "</div>\n";
echo "    <!--/services-->\n";
echo "    <section class=\"w3l-services2\" id=\"services\">\n";
echo "        <div id=\"cwp23-block\" class=\"py-5\">\n";
echo "            <div class=\"container py-lg-5\">\n";
echo "                <div class=\"row cwp23-content mt-lg-5 mt-4\">\n";
echo "                    <div class=\"col-lg-6 cwp23-img\">\n";
echo "                        <h6 class=\"title-subhny mb-2\"><span>我们做什麼？</span></h6>\n";
echo "                        <h3 class=\"title-w3l mb-4\">文本 <br>\n";
echo "                            <span class=\"span-bold\">文本</span>\n";
echo "                        </h3>\n";
echo "                        <p class=\"mt-4\">文本\n";
echo "\n";
echo "                        </p>\n";
echo "\n";
echo "                        <div class=\"w3l-button mt-lg-5 mt-4\">\n";
echo "                            <a href=\"services.html\" class=\"btn btn-style btn-primary mt-2\">了解更多 <span class=\"fas fa-angle-double-right ms-2\"></span></a>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                    <div class=\"col-lg-6 cwp23-text mt-lg-0 mt-5 ps-lg-5\">\n";
echo "                        <div class=\"cwp23-text-cols\">\n";
echo "                            <div class=\"column\">\n";
echo "                                <a href=\"#\"><img src=\"assets/images/g2.jpg\" alt=\"\" class=\"radius-image img-fluid\"></a>\n";
echo "                            </div>\n";
echo "                            <div class=\"column\">\n";
echo "                                <a href=\"#\"><img src=\"assets/images/g3.jpg\" alt=\"\" class=\"radius-image img-fluid\"></a>\n";
echo "                            </div>\n";
echo "                            <div class=\"column\">\n";
echo "                                <a href=\"#\"><img src=\"assets/images/g4.jpg\" alt=\"\" class=\"radius-image img-fluid\"></a>\n";
echo "                            </div>\n";
echo "                            <div class=\"column\">\n";
echo "                                <a href=\"#\"><img src=\"assets/images/g5.jpg\" alt=\"\" class=\"radius-image img-fluid\"></a>\n";
echo "                            </div>\n";
echo "\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </section>\n";
echo "\n";
echo "    <!--//services-->\n";
echo "<div style=\"margin: 8px auto; display: block; text-align:center;\">\n";
echo "\n";
echo "<!---728x90--->\n";
echo " \n";
echo "</div>\n";
echo "    <!--/grids-->\n";
echo "    <section class=\"w3l-grids-3 py-5\">\n";
echo "        <div class=\"container py-md-5 py-3\">\n";
echo "            <div class=\"row bottom-ab-grids align-items-center\">\n";
echo "                <div class=\"header-sec text-center\">\n";
echo "                    <h6 class=\"title-subhny mb-2\"><span>流程</span></h6>\n";
echo "                    <h3 class=\"title-w3l mb-3\">小白<br>\n";
echo "                        也能\n";
echo "                        <span class=\"span-bold\">会</span>\n";
echo "                    </h3>\n";
echo "\n";
echo "                </div>\n";
echo "\n";
echo "            </div>\n";
echo "            <div class=\"row bottom_grids pt-md-3 text-left\">\n";
echo "                <div class=\"col-lg-4 col-md-6 mt-5\">\n";
echo "                    <div class=\"grid-block\">\n";
echo "                        <a href=\"blog-single.html\" class=\"d-block p-lg-4 p-3\">\n";
echo "                            <span class=\"fas fa-file-alt\" aria-hidden=\"true\"></span>\n";
echo "                            <h4 class=\"my-3\">基本信息</h4>\n";
echo "                            <p class=\"\">填寫基本信息</p>\n";
echo "                        </a>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "                <div class=\"col-lg-4 col-md-6 mt-5\">\n";
echo "                    <div class=\"grid-block\">\n";
echo "                        <a href=\"blog-single.html\" class=\"d-block p-lg-4 p-3\">\n";
echo "                            <span class=\"fas fa-holly-berry\" aria-hidden=\"true\"></span>\n";
echo "                            <h4 class=\"my-3\">檢查</h4>\n";
echo "                            <p class=\"\">依據行情 </p>\n";
echo "                        </a>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "                <div class=\"col-lg-4 col-md-6 mt-5\">\n";
echo "                    <div class=\"grid-block\">\n";
echo "                        <a href=\"blog-single.html\" class=\"d-block p-lg-4 p-3\">\n";
echo "                            <span class=\"fas fa-american-sign-language-interpreting\" aria-hidden=\"true\"></span>\n";
echo "                            <h4 class=\"my-3\">沟通</h4>\n";
echo "\n";
echo "                            <p class=\"\">了解细节 </p>\n";
echo "                        </a>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "                <div class=\"col-lg-4 col-md-6 mt-5\">\n";
echo "                    <div class=\"grid-block\">\n";
echo "                        <a href=\"blog-single.html\" class=\"d-block p-lg-4 p-3\">\n";
echo "                            <span class=\"fa fa-cubes\" aria-hidden=\"true\"></span>\n";
echo "                            <h4 class=\"my-3\">完成</h4>\n";
echo "                            <p class=\"\">打包帶走！ </p>\n";
echo "                        </a>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "                <div class=\"col-lg-4 col-md-6 mt-5\">\n";
echo "                    <div class=\"grid-block\">\n";
echo "                        <a href=\"blog-single.html\" class=\"d-block p-lg-4 p-3\">\n";
echo "                            <span class=\"fas fa-chart-pie\" aria-hidden=\"true\"></span>\n";
echo "                            <h4 class=\"my-3\">填寫信息</h4>\n";
echo "                            <p class=\"\">胜利就在眼前</p>\n";
echo "                        </a>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "                <div class=\"col-lg-4 col-md-6 mt-5\">\n";
echo "                    <div class=\"grid-block\">\n";
echo "                        <a href=\"blog-single.html\" class=\"d-block p-lg-4 p-3\">\n";
echo "                            <span class=\"fas fa-headset\" aria-hidden=\"true\"></span>\n";
echo "                            <h4 class=\"my-3\">售後</h4>\n";
echo "                            <p class=\"\">三个月支持 </p>\n";
echo "                        </a>\n";
echo "                    </div>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "    </section>\n";
echo "    <!--//grids-->\n";
echo "    <!--/w3l-services3-->\n";
echo "    <!--<section class=\"w3l-services3\">-->\n";
echo "    <!--    <div class=\"new-block\">-->\n";
echo "    <!--        <div class=\"container py-5\">-->\n";
echo "    <!--            <div class=\"middle-section py-lg-5 py-4\">-->\n";
echo "    <!--                <div class=\"section-width\">-->\n";
echo "    <!--                    <h6 class=\"title-subhny mb-2\"><span>Why Choose Us</span></h6>-->\n";
echo "    <!--                    <h3 class=\"title-w3l two mb-4\">Get in touch with us and we’ll help-->\n";
echo "    <!--                        <span class=\"span-bold\">your business.</span>-->\n";
echo "    <!--                    </h3>-->\n";
echo "    <!--                </div>-->\n";
echo "    <!--                <div class=\"link-list-menu\">-->\n";
echo "    <!--                    <p class=\"\">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nulla non ipsum soluta-->\n";
echo "    <!--                        perferendis-->\n";
echo "    <!--                        veniam qui esse magnam commodi quisquam vitae labore nemo at voluptatem, totam, minima recusandae-->\n";
echo "    <!--                        assumenda.</p>-->\n";
echo "    <!--                    <div class=\"w3l-two-buttons\">-->\n";
echo "    <!--                        <a href=\"about.html\" class=\"btn btn-primary btn-white btn-style mt-lg-5 mt-4\"> Read More <span class=\"fas fa-angle-double-right ml-2\"></span></a>-->\n";
echo "    <!--                        <a href=\"about.html\" class=\"btn btn-style btn-secondary mt-lg-5 mt-4 ms-sm-3\">Read More <span class=\"fas fa-angle-double-right ml-2\"></span> </a>-->\n";
echo "    <!--                    </div>-->\n";
echo "    <!--                </div>-->\n";
echo "    <!--            </div>-->\n";
echo "    <!--        </div>-->\n";
echo "    <!--    </div>-->\n";
echo "    <!--</section>-->\n";
echo "    <!--//w3l-services3-->\n";
echo "	<div style=\"margin: 8px auto; display: block; text-align:center;\">\n";
echo "\n";
echo "<!---728x90--->\n";
echo " \n";
echo "</div>\n";
echo "    <!--/w3l-pricing-->\n";
echo "    <!--<section class=\"w3l-pricing-sec py-5\" id=\"pricing\">-->\n";
echo "    <!--    <div class=\"container py-md-5 py-2\">-->\n";
echo "    <!--        <div class=\"title-content text-center\">-->\n";
echo "    <!--            <h6 class=\"title-subhny mb-2\"><span>Get Started</span></h6>-->\n";
echo "    <!--            <h3 class=\"title-w3l mb-4\">Pricing-->\n";
echo "    <!--                <span class=\"span-bold\">Plans</span>-->\n";
echo "    <!--            </h3>-->\n";
echo "    <!--        </div>-->\n";
echo "    <!--        <div class=\"row pricing-main-grids mt-3\">-->\n";
echo "    <!--            <div class=\"col-lg-4 col-md-6 pricing-main-grid mt-sm-5 mt-4\">-->\n";
echo "    <!--                <div class=\"w3-pricing-inner-inf\">-->\n";
echo "    <!--                    <div class=\"pricing-header\">-->\n";
echo "    <!--                        <h4>Basic</h4>-->\n";
echo "    <!--                        <p>A beautiful, simple website</p>-->\n";
echo "    <!--                        <div class=\"price-wrapper mt-4\">-->\n";
echo "    <!--                            <div class=\"price\">-->\n";
echo "    <!--                                <h3 class=\"currency\">From $</h3>-->\n";
echo "    <!--                                <h3 class=\"heading headin-h3\">39</h3>-->\n";
echo "    <!--                            </div>-->\n";
echo "    <!--                        </div>-->\n";
echo "\n";
echo "    <!--                    </div>-->\n";
echo "    <!--                    <div class=\"pricing-body\">-->\n";
echo "    <!--                        <div class=\"inner\">-->\n";
echo "    <!--                            <ul class=\"list-style\">-->\n";
echo "    <!--                                <li><span class=\"fa fa-check me-2\" aria-hidden=\"true\"></span> 5 Projects</li>-->\n";
echo "    <!--                                <li><span class=\"fa fa-check me-2\" aria-hidden=\"true\"></span> 2100K API Access</li>-->\n";
echo "    <!--                                <li><span class=\"fa fa-check me-2\" aria-hidden=\"true\"></span> 200MB Storag</li>-->\n";
echo "    <!--                                <li><span class=\"fa fa-check me-2\" aria-hidden=\"true\"></span> Weekly Reports</li>-->\n";
echo "    <!--                                <li><span class=\"fa fa-check me-2\" aria-hidden=\"true\"></span> 24/7 Support</li>-->\n";
echo "    <!--                            </ul>-->\n";
echo "    <!--                        </div>-->\n";
echo "    <!--                        <div class=\"pricing-get-button mt-3\">-->\n";
echo "    <!--                            <a class=\"btn btn-secondary btn-style mt-4 d-block\" href=\"#\">Get Started-->\n";
echo "    <!--                                Today </a>-->\n";
echo "    <!--                        </div>-->\n";
echo "    <!--                    </div>-->\n";
echo "    <!--                </div>-->\n";
echo "    <!--            </div>-->\n";
echo "    <!--            <div class=\"col-lg-4 col-md-6 pricing-main-grid mt-sm-5 mt-4\">-->\n";
echo "    <!--                <div class=\"w3-pricing-inner-inf\">-->\n";
echo "    <!--                    <div class=\"pricing-header set-2\">-->\n";
echo "    <!--                        <h4>Standard</h4>-->\n";
echo "    <!--                        <p>A beautiful, simple website</p>-->\n";
echo "    <!--                        <div class=\"price-wrapper mt-4\">-->\n";
echo "    <!--                            <div class=\"price\">-->\n";
echo "    <!--                                <h3 class=\"currency\">From $</h3>-->\n";
echo "    <!--                                <h3 class=\"heading headin-h3\">69</h3>-->\n";
echo "    <!--                            </div>-->\n";
echo "    <!--                        </div>-->\n";
echo "    <!--                    </div>-->\n";
echo "    <!--                    <div class=\"pricing-body\">-->\n";
echo "    <!--                        <div class=\"inner\">-->\n";
echo "    <!--                            <ul class=\"list-style\">-->\n";
echo "    <!--                                <li><span class=\"fa fa-check me-2\" aria-hidden=\"true\"></span> 10 Projects</li>-->\n";
echo "    <!--                                <li><span class=\"fa fa-check me-2\" aria-hidden=\"true\"></span> 2100K API Access</li>-->\n";
echo "    <!--                                <li><span class=\"fa fa-check me-2\" aria-hidden=\"true\"></span> 300MB Storag</li>-->\n";
echo "    <!--                                <li><span class=\"fa fa-check me-2\" aria-hidden=\"true\"></span> Weekly Reports</li>-->\n";
echo "    <!--                                <li><span class=\"fa fa-check me-2\" aria-hidden=\"true\"></span> 24/7 Support</li>-->\n";
echo "    <!--                            </ul>-->\n";
echo "    <!--                        </div>-->\n";
echo "    <!--                        <div class=\"pricing-get-button mt-3\">-->\n";
echo "    <!--                            <a class=\"btn btn-secondary btn-style mt-4 d-block\" href=\"#\">Get Started-->\n";
echo "    <!--                                Today </a>-->\n";
echo "    <!--                        </div>-->\n";
echo "    <!--                    </div>-->\n";
echo "    <!--                </div>-->\n";
echo "    <!--            </div>-->\n";
echo "    <!--            <div class=\"col-lg-4 col-md-6 pricing-main-grid mt-sm-5 mt-4\">-->\n";
echo "    <!--                <div class=\"w3-pricing-inner-inf\">-->\n";
echo "    <!--                    <div class=\"pricing-header set-3\">-->\n";
echo "    <!--                        <h4>Premium Plan</h4>-->\n";
echo "    <!--                        <p>A beautiful, simple website</p>-->\n";
echo "    <!--                        <div class=\"price-wrapper mt-4\">-->\n";
echo "    <!--                            <div class=\"price\">-->\n";
echo "    <!--                                <h3 class=\"currency\">From $</h3>-->\n";
echo "    <!--                                <h3 class=\"heading headin-h3\">99</h3>-->\n";
echo "    <!--                            </div>-->\n";
echo "    <!--                        </div>-->\n";
echo "    <!--                    </div>-->\n";
echo "    <!--                    <div class=\"pricing-body\">-->\n";
echo "    <!--                        <div class=\"inner\">-->\n";
echo "    <!--                            <ul class=\"list-style\">-->\n";
echo "    <!--                                <li><span class=\"fa fa-check me-2\" aria-hidden=\"true\"></span> 15 Projects</li>-->\n";
echo "    <!--                                <li><span class=\"fa fa-check me-2\" aria-hidden=\"true\"></span> 2100K API Access</li>-->\n";
echo "    <!--                                <li><span class=\"fa fa-check me-2\" aria-hidden=\"true\"></span> 400MB Storag</li>-->\n";
echo "    <!--                                <li><span class=\"fa fa-check me-2\" aria-hidden=\"true\"></span> Weekly Reports</li>-->\n";
echo "    <!--                                <li><span class=\"fa fa-check me-2\" aria-hidden=\"true\"></span>24/7 Support</li>-->\n";
echo "    <!--                            </ul>-->\n";
echo "    <!--                        </div>-->\n";
echo "    <!--                        <div class=\"pricing-get-button mt-3\">-->\n";
echo "    <!--                            <a class=\"btn btn-secondary btn-style mt-4 d-block\" href=\"#\">Get Started-->\n";
echo "    <!--                                Today </a>-->\n";
echo "    <!--                        </div>-->\n";
echo "    <!--                    </div>-->\n";
echo "    <!--                </div>-->\n";
echo "    <!--            </div>-->\n";
echo "    <!--        </div>-->\n";
echo "    <!--    </div>-->\n";
echo "    <!--</section>-->\n";
echo "    <!-- //w3l-pricing-->\n";
echo "    <!--/w3l-footer-29-main-->\n";
echo "    <footer class=\"w3l-footer-29-main\">\n";
echo "        <div class=\"footer-29 py-5\">\n";
echo "            <div class=\"container py-lg-4\">\n";
echo "                <div class=\"row align-items-center mb-3\">\n";
echo "                    <h2 class=\"sign-left col-lg-7\"> 加入我們的交流群</h2>\n";
echo "                    <div class=\"footerw3-btn col-lg-5 ps-lg-5\"><a href=\"https://qm.qq.com/q/3z10gQ6Fzy\" class=\"btn btn-secondary btn-style\"> QQGroup <span class=\"fas fa-angle-double-right ms-2\"></span></a></div>\n";
echo "                </div>\n";
echo "\n";
echo "                <div class=\"row footer-top-29 mt-md-5 mt-4\">\n";
echo "                    <div class=\"col-lg-4 col-md-6 footer-list-29 footer-1 pe-lg-5\">\n";
echo "                        <h6 class=\"footer-title-29\">关于</h6>\n";
echo "                        <div class=\"footer-listw3-grids\">\n";
echo "                            <p class=\"pe-lg-4\">个人测试网页</p>\n";
echo "                            <div class=\"w3pt-call-box mt-4\">\n";
echo "                                <div class=\"w3pt-call-info\">\n";
echo "                                    <h5>联系我们</h5>\n";
echo "\n";
echo "                                    <h5><a href=\"tel:+1(21) 234 557 456\"><i class=\"fas fa-phone-alt me-1\"></i> 114514</a></h5>\n";
echo "                                    <h5><a href=\"tel:+1(21) 234 4568\"><i class=\"far fa-envelope me-1\"></i> 114514@qq.com</a></h5>\n";
echo "\n";
echo "                                </div>\n";
echo "\n";
echo "                            </div>\n";
echo "                        </div>\n";
echo "\n";
echo "                    </div>\n";
echo "                    <div class=\"col-lg-2 col-md-6 footer-list-29 footer-3 mt-lg-0 mt-5\">\n";
echo "                        <h6 class=\"footer-title-29\">友情链接</h6>\n";
echo "                        <div class=\"footer-listw3-grids\">\n";
echo "                            <ul class=\"footer-listw3\">\n";
echo "                                <li><a href=\"http://www.wwk12450.com/\">国家反诈中心</a></li>\n";
echo "                                <li><a href=\"#\">2</a></li>\n";
echo "                                <li><a href=\"#\">3</a></li>\n";
echo "                                <li><a href=\"#\">4</a></li>\n";
echo "                                <li><a href=\"#\">5</a></li>\n";
echo "                                <li><a href=\"#\">6</a></li>\n";
echo "\n";
echo "                            </ul>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "                    <div class=\"col-lg-2 col-md-6 footer-list-29 footer-3 mt-lg-0 mt-5\">\n";
echo "                        <h6 class=\"footer-title-29\">服务</h6>\n";
echo "                        <div class=\"footer-listw3-grids\">\n";
echo "                            <ul class=\"footer-listw3\">\n";
echo "                                <li><a href=\"#lift\">商品</a></li>\n";
echo "                                <li><a href=\"#cardio\">售后</a></li>\n";
echo "                                <li><a href=\"#fit\">3</a></li>\n";
echo "                                <li><a href=\"#tips\">4</a></li>\n";
echo "                                <li><a href=\"#tips\">5</a></li>\n";
echo "                                <li><a href=\"#tips\">6</a></li>\n";
echo "                            </ul>\n";
echo "                        </div>\n";
echo "                    </div>\n";
echo "\n";
echo "                    <div class=\"col-lg-4 col-md-6 footer-list-29 footer-4 mt-lg-0 mt-5 ps-lg-5\">\n";
echo "                        <h6 class=\"footer-title-29\">获取最新信息</h6>\n";
echo "                        <ul class=\"footer-listw3\">\n";
echo "                        <li><a href=\"https://qm.qq.com/q/3z10gQ6Fzy\">移步Q群</a></li>\n";
echo "                        </ul>\n";
echo "\n";
echo "                        \n";
echo "                        \n";
echo "                    </div>\n";
echo "                </div>\n";
echo "                <div class=\"bottom-copies text-center\">\n";
echo "                    <p class=\"copy-footer-29\"> All rights reserved. \n";
echo "                    </p>\n";
echo "                </div>\n";
echo "            </div>\n";
echo "        </div>\n";
echo "\n";
echo "        <!-- move top -->\n";
echo "        <button onclick=\"topFunction()\" id=\"movetop\" title=\"Go to top\">\n";
echo "            <span class=\"fa fa-angle-up\"></span>\n";
echo "        </button>\n";
echo "        <script>\n";
echo "            // When the user scrolls down 20px from the top of the document, show the button\n";
echo "            window.onscroll = function() {\n";
echo "                scrollFunction()\n";
echo "            };\n";
echo "\n";
echo "            function scrollFunction() {\n";
echo "                if (document.body.scrollTop > 20 || document.documentElement.scrollTop > 20) {\n";
echo "                    document.getElementById(\"movetop\").style.display = \"block\";\n";
echo "                } else {\n";
echo "                    document.getElementById(\"movetop\").style.display = \"none\";\n";
echo "                }\n";
echo "            }\n";
echo "\n";
echo "            // When the user clicks on the button, scroll to the top of the document\n";
echo "            function topFunction() {\n";
echo "                document.body.scrollTop = 0;\n";
echo "                document.documentElement.scrollTop = 0;\n";
echo "            }\n";
echo "\n";
echo "        </script>\n";
echo "        <!-- //move top -->\n";
echo "\n";
echo "    </footer>\n";
echo "    <!--//footer-9 -->\n";
echo "    <!-- Js scripts -->\n";
echo "    <!-- Template JavaScript -->\n";
echo "    <script src=\"assets/js/jquery-3.3.1.min.js\"></script>\n";
echo "    <script src=\"assets/js/theme-change.js\"></script>\n";
echo "    <!-- Lightbox --\n";
echo "    <script src=\"assets/js/jquery-2.1.4.min.js\"></script>\n";
echo "    <script src=\"assets/js/simpleLightbox.js\"></script>\n";
echo "    <script>\n";
echo "        $(\'.w3layouts_gallery_grid a\').simpleLightbox();\n";
echo "\n";
echo "    </script>\n";
echo "    <!-- //Lightbox -->\n";
echo "    <script src=\"assets/js/jquery-1.9.1.min.js\"></script>\n";
echo "    <!-- faq -->\n";
echo "    <script>\n";
echo "        const items = document.querySelectorAll(\".accordion button\");\n";
echo "\n";
echo "        function toggleAccordion() {\n";
echo "            const itemToggle = this.getAttribute(\'aria-expanded\');\n";
echo "\n";
echo "            for (i = 0; i < items.length; i++) {\n";
echo "                items[i].setAttribute(\'aria-expanded\', \'false\');\n";
echo "            }\n";
echo "\n";
echo "            if (itemToggle == \'false\') {\n";
echo "                this.setAttribute(\'aria-expanded\', \'true\');\n";
echo "            }\n";
echo "        }\n";
echo "\n";
echo "        items.forEach(item => item.addEventListener(\'click\', toggleAccordion));\n";
echo "\n";
echo "    </script>\n";
echo "    <!-- //faq -->\n";
echo "    <script src=\"assets/js/easyResponsiveTabs.js\"></script>\n";
echo "    <!--Plug-in Initialisation-->\n";
echo "    <script type=\"text/javascript\">\n";
echo "        $(document).ready(function() {\n";
echo "            //Horizontal Tab\n";
echo "            $(\'#parentHorizontalTab\').easyResponsiveTabs({\n";
echo "                type: \'default\', //Types: default, vertical, accordion\n";
echo "                width: \'auto\', //auto or any width like 600px\n";
echo "                fit: true, // 100% fit in a container\n";
echo "                tabidentify: \'hor_1\', // The tab groups identifier\n";
echo "                activate: function(event) { // Callback function if tab is switched\n";
echo "                    var $tab = $(this);\n";
echo "                    var $info = $(\'#nested-tabInfo\');\n";
echo "                    var $name = $(\'span\', $info);\n";
echo "                    $name.text($tab.text());\n";
echo "                    $info.show();\n";
echo "                }\n";
echo "            });\n";
echo "        });\n";
echo "\n";
echo "    </script>\n";
echo "    <script src=\"assets/js/circles.js\"></script>\n";
echo "    <!-- owlcarousel -->\n";
echo "    <script src=\"assets/js/owl.carousel.js\"></script>\n";
echo "    <!-- script for banner slider-->\n";
echo "    <script>\n";
echo "        $(document).ready(function() {\n";
echo "            $(\'.owl-one\').owlCarousel({\n";
echo "                loop: true,\n";
echo "                margin: 0,\n";
echo "                nav: false,\n";
echo "                responsiveClass: true,\n";
echo "                autoplay: true,\n";
echo "                autoplayTimeout: 5000,\n";
echo "                autoplaySpeed: 1000,\n";
echo "                autoplayHoverPause: false,\n";
echo "                responsive: {\n";
echo "                    0: {\n";
echo "                        items: 1\n";
echo "                    },\n";
echo "                    480: {\n";
echo "                        items: 1\n";
echo "                    },\n";
echo "                    667: {\n";
echo "                        items: 1\n";
echo "                    },\n";
echo "                    1000: {\n";
echo "                        items: 1\n";
echo "                    }\n";
echo "                }\n";
echo "            })\n";
echo "        })\n";
echo "\n";
echo "    </script>\n";
echo "    <!-- //script -->\n";
echo "    <!-- script for tesimonials carousel slider -->\n";
echo "    <script>\n";
echo "        $(document).ready(function() {\n";
echo "            $(\"#owl-demo1\").owlCarousel({\n";
echo "                loop: true,\n";
echo "                margin: 200,\n";
echo "                nav: false,\n";
echo "                responsiveClass: true,\n";
echo "                responsive: {\n";
echo "                    0: {\n";
echo "                        items: 1,\n";
echo "                        nav: false\n";
echo "                    },\n";
echo "                    736: {\n";
echo "                        items: 1,\n";
echo "                        nav: false\n";
echo "                    },\n";
echo "                    1000: {\n";
echo "                        items: 2,\n";
echo "                        nav: false,\n";
echo "                        margin: 30,\n";
echo "                        loop: false\n";
echo "                    }\n";
echo "                }\n";
echo "            })\n";
echo "        })\n";
echo "\n";
echo "    </script>\n";
echo "    <!-- //script for tesimonials carousel slider -->\n";
echo "    <!-- video popup -->\n";
echo "    <script src=\"assets/js/jquery.magnific-popup.min.js\"></script>\n";
echo "    <script>\n";
echo "        $(document).ready(function() {\n";
echo "            $(\'.popup-with-zoom-anim\').magnificPopup({\n";
echo "                type: \'inline\',\n";
echo "\n";
echo "                fixedContentPos: false,\n";
echo "                fixedBgPos: true,\n";
echo "\n";
echo "                overflowY: \'auto\',\n";
echo "\n";
echo "                closeBtnInside: true,\n";
echo "                preloader: false,\n";
echo "\n";
echo "                midClick: true,\n";
echo "                removalDelay: 300,\n";
echo "                mainClass: \'my-mfp-zoom-in\'\n";
echo "            });\n";
echo "\n";
echo "            $(\'.popup-with-move-anim\').magnificPopup({\n";
echo "                type: \'inline\',\n";
echo "\n";
echo "                fixedContentPos: false,\n";
echo "                fixedBgPos: true,\n";
echo "\n";
echo "                overflowY: \'auto\',\n";
echo "\n";
echo "                closeBtnInside: true,\n";
echo "                preloader: false,\n";
echo "\n";
echo "                midClick: true,\n";
echo "                removalDelay: 300,\n";
echo "                mainClass: \'my-mfp-slide-bottom\'\n";
echo "            });\n";
echo "        });\n";
echo "\n";
echo "    </script>\n";
echo "    <!-- //video popup -->\n";
echo "    <!-- MENU-JS -->\n";
echo "    <script>\n";
echo "        $(window).on(\"scroll\", function() {\n";
echo "            var scroll = $(window).scrollTop();\n";
echo "\n";
echo "            if (scroll >= 80) {\n";
echo "                $(\"#site-header\").addClass(\"nav-fixed\");\n";
echo "            } else {\n";
echo "                $(\"#site-header\").removeClass(\"nav-fixed\");\n";
echo "            }\n";
echo "        });\n";
echo "\n";
echo "        //Main navigation Active Class Add Remove\n";
echo "        $(\".navbar-toggler\").on(\"click\", function() {\n";
echo "            $(\"header\").toggleClass(\"active\");\n";
echo "        });\n";
echo "        $(document).on(\"ready\", function() {\n";
echo "            if ($(window).width() > 991) {\n";
echo "                $(\"header\").removeClass(\"active\");\n";
echo "            }\n";
echo "            $(window).on(\"resize\", function() {\n";
echo "                if ($(window).width() > 991) {\n";
echo "                    $(\"header\").removeClass(\"active\");\n";
echo "                }\n";
echo "            });\n";
echo "        });\n";
echo "\n";
echo "    </script>\n";
echo "    <!-- //MENU-JS -->\n";
echo "\n";
echo "    <!-- disable body scroll which navbar is in active -->\n";
echo "    <script>\n";
echo "        $(function() {\n";
echo "            $(\'.navbar-toggler\').click(function() {\n";
echo "                $(\'body\').toggleClass(\'noscroll\');\n";
echo "            })\n";
echo "        });\n";
echo "\n";
echo "    </script>\n";
echo "    <!-- //disable body scroll which navbar is in active -->\n";
echo "\n";
echo "    <!-- //bootstrap -->\n";
echo "    <script src=\"assets/js/bootstrap.min.js\"></script>\n";
echo "\n";
echo "\n";
echo "</body>\n";
echo "\n";
echo "</html>\n";
echo "\n";
?>